node ('xamarin') 
{
timestamps{
    stage 'Checkout' 
    try    {	
	  //checkout the xamarinandroid-samplebrowser Source	
	  checkout([$class: 'GitSCM', branches: [[name: '*/$githubSourceBranch']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'xamarinandroid-samplebrowser']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: env.GiteaCredentialID, url: 'https://gitea.syncfusion.com/essential-studio/xamarinandroid-samplebrowser.git']]])
	  
	  //checkout the essentialstudio-common Source
	  checkout([$class: 'GitSCM', branches: [[name: '*/development']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'essentialstudio-common']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: env.GiteaCredentialID, url: 'https://gitea.syncfusion.com/essential-studio/essentialstudio-common.git']]])
	  	  
     }
    catch(Exception e)    {	 
	    echo "Exception in 'Checkout' stage \r\n"+ e
        currentBuild.result = 'FAILURE'		
    } 
if(currentBuild.result != 'FAILURE')
{ 
	stage('Install Software') {
		try
		{
			
			nodejs(nodeJSInstallationName: 'nodejs-16.17.1') {
			    bat 'npm config ls'
			}

			env.PATH = "C:\\tools\\jenkins.plugins.nodejs.tools.NodeJSInstallation\\nodejs-16.17.1;${env.PATH}"
			bat 'npm -v'
			bat 'npm install --location=global appcenter-cli'

			bat 'powershell.exe -ExecutionPolicy ByPass -File ./xamarinandroid-samplebrowser/Install.ps1'
			echo "Software installation completed"
		}
		 catch(Exception e)
		 {
		    echo "Exception in software installation stage \r\n"+e
			currentBuild.result = 'FAILURE'
		 }
	}
}
if(currentBuild.result != 'FAILURE')
{		
	stage 'Build Source'
	try	{	    
 	 
	 gitlabCommitStatus("Build")
	 {
	   
	  bat 'powershell.exe -ExecutionPolicy ByPass -File xamarinandroid-samplebrowser/build/build.ps1 -Script '+env.WORKSPACE+"/xamarinandroid-samplebrowser/build/build.cake -Target build  -nugetserverurl "+env.nugetserverurls +' -StudioVersion  '+env.studio_version
	 
	 }
     
	 def files = findFiles(glob: '**/cireports/errorlogs/*.txt')

        if(files.size() > 0)
        {
           currentBuild.result = 'FAILURE'
        }
    }
	 catch(Exception e) 
    { 
	    echo "Exception in 'Build' stage \r\n"+ e
		currentBuild.result = 'FAILURE'
    }
}
 
if(currentBuild.result != 'FAILURE' && env.publishBranch.contains(githubSourceBranch))
{
	stage 'Publish'
	try
	{
	  //method to get release notes content
	     env.PATH = "C:\\Program Files\\Git\\mingw64\\bin;${env.PATH}"  
       def branchCommit = '"'+'https://gitea.syncfusion.com/api/v1/repos/essential-studio/xamarinandroid-samplebrowser/pulls/'+ env.pullRequestId +'/commits'
	   String branchCommitDetails = bat returnStdout: true, script: 'curl -H "Accept: application/json" -u Syncfusion-Gitea:' +env.GiteaBuildAutomation_PrivateToken+" "+branchCommit
	  def splitMessageDetails = branchCommitDetails.split('"message": "')
	   def releaseNotesContent=""; 
		for(int k=1; k<splitMessageDetails.size();k++)
		{
			releaseNotesContent += splitMessageDetails[k].split('"tree":')[0].replace("\",","");
		}
		if (releaseNotesContent) 
		{  
		   writeFile file: env.WORKSPACE+"/cireports/releasenotes/releasenotes.txt", text: releaseNotesContent
		}
		else  
		{
		   writeFile file: env.WORKSPACE+"/cireports/releasenotes/releasenotes.txt", text: "No commit details found for this job."
		}
		
	   	  
	  gitlabCommitStatus("Publish")
	    {  
	        bat 'powershell.exe -ExecutionPolicy ByPass -File xamarinandroid-samplebrowser/build/build.ps1 -Script '+env.WORKSPACE+"/xamarinandroid-samplebrowser/build/build.cake -Target publish -apitoken " +env.Hockey_apitoken + " -Scheduler "+env.isScheduler +" -MachineIP "+env.MachineIP+" -SourceBranch "+env.githubSourceBranch
	        
	    }
	}
	catch(Exception e) 
	{
		echo "Exception in 'Publish' stage \r\n"+ e
		currentBuild.result = 'FAILURE'
	}
}
	stage 'Delete Workspace'
	
	// Archiving artifacts when the folder was not empty	
    def files = findFiles(glob: '**/cireports/**/*.*')      
    
    if(files.size() > 0) 		
    { 		
        archiveArtifacts artifacts: 'cireports/', excludes: null 		
    }
	 
	step([$class: 'WsCleanup'])
}
}
