node ('xamarin') 
{
timestamps{
    stage 'Checkout' 
    try    {	
	  //checkout the xamarinandroid-samplebrowser Source	
	  checkout([$class: 'GitSCM', branches: [[name: '*/$gitlabSourceBranch']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'xamarinandroid-samplebrowser']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: env.gitlabCredentialId, url: 'https://gitlab.syncfusion.com/essential-studio/xamarinandroid-samplebrowser.git']]])
	  
	  //checkout the essentialstudio-common Source
	  checkout([$class: 'GitSCM', branches: [[name: '*/development']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'essentialstudio-common']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: env.gitlabCredentialId, url: 'https://gitlab.syncfusion.com/essential-studio/essentialstudio-common.git']]])
	  	  
     }
    catch(Exception e)    {	 
	    echo "Exception in 'Checkout' stage \r\n"+ e
        currentBuild.result = 'FAILURE'		
    } 

if(currentBuild.result != 'FAILURE')
{		
	stage 'Build Source'
	try	{	    
 	 
	 gitlabCommitStatus("Build")
	 {
	   
	  bat 'powershell.exe -ExecutionPolicy ByPass -File xamarinandroid-samplebrowser/build/build.ps1 -Script '+env.WORKSPACE+"/xamarinandroid-samplebrowser/build/build.cake -Target build  -nugetserverurl "+env.nugetserverurls +' -StudioVersion  '+env.studio_version
	 
	 }
     
	 def files = findFiles(glob: '**/cireports/errorlogs/*.txt')

        if(files.size() > 0)
        {
           currentBuild.result = 'FAILURE'
        }
    }
	 catch(Exception e) 
    { 
	    echo "Exception in 'Build' stage \r\n"+ e
		currentBuild.result = 'FAILURE'
    }
}
 
if(currentBuild.result != 'FAILURE' && env.publishBranch.contains(gitlabSourceBranch))
{
	stage 'Publish'
	try
	{
	  //method to get release notes content
	     env.PATH = "C:\\Program Files\\Git\\mingw64\\bin;${env.PATH}"  
       def branchCommit = '"'+'https://gitlab.syncfusion.com/api/v4/projects/820/merge_requests/'+env.MergeRequestId+'/commits'
	   String branchCommitDetails = bat returnStdout: true, script: 'curl -s --request GET --header PRIVATE-TOKEN:' +env.BuildAutomation_PrivateToken+" "+branchCommit
	   def splitCommitDetails=branchCommitDetails.split('\n')
	   def splitMessageDetails = splitCommitDetails[2].split('"message":')
	   def releaseNotesContent=""; 
		for(int k=1; k<splitMessageDetails.size();k++)
		{
			def commitDetails = splitMessageDetails[k].split('"author_email":')
			for(int j=1; j<commitDetails.size(); j++)
			{			
				 releaseNotesContent+=commitDetails[0].replace(',"author_name":',' - ').replace('\\n','').replace('",','"')+"\r\n";
			}
		}
		if (releaseNotesContent) 
		{  
		   writeFile file: env.WORKSPACE+"/cireports/releasenotes/releasenotes.txt", text: releaseNotesContent
		}
		else  
		{
		   writeFile file: env.WORKSPACE+"/cireports/releasenotes/releasenotes.txt", text: "No commit details found for this job."
		}
	  
	  gitlabCommitStatus("Publish")
	    {  
	        bat 'powershell.exe -ExecutionPolicy ByPass -File xamarinandroid-samplebrowser/build/build.ps1 -Script '+env.WORKSPACE+"/xamarinandroid-samplebrowser/build/build.cake -Target publish -apitoken " +env.Hockey_apitoken + " -Scheduler "+env.isScheduler +" -MachineIP "+env.MachineIP+" -SourceBranch "+env.gitlabSourceBranch
	        
	    }
	}
	catch(Exception e) 
	{
		echo "Exception in 'Publish' stage \r\n"+ e
		currentBuild.result = 'FAILURE'
	}
}
	stage 'Delete Workspace'
	
	// Archiving artifacts when the folder was not empty	
    def files = findFiles(glob: '**/cireports/**/*.*')      
    
    if(files.size() > 0) 		
    { 		
        archiveArtifacts artifacts: 'cireports/', excludes: null 		
    }
	 
	step([$class: 'WsCleanup'])
}
}