#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleBrowser.SfTabView.Droid.Resource", IsApplication=true)]

namespace SampleBrowser.SfTabView.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int AngleSofa = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int Apple = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int Banana = 2130771970;
			
			// aapt resource value: 0x7F010004
			public const int Blackshoe = 2130771972;
			
			// aapt resource value: 0x7F010003
			public const int BlackSofa = 2130771971;
			
			// aapt resource value: 0x7F010005
			public const int Blueberry = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int Boots = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int Canvas = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int Chair = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int Friends_Toy = 2130771977;
			
			// aapt resource value: 0x7F01000B
			public const int Graycanvas = 2130771979;
			
			// aapt resource value: 0x7F01000A
			public const int GraySofa = 2130771978;
			
			// aapt resource value: 0x7F01000C
			public const int Leather = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int Mario = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int Orange = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int People_Circle23 = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int Redcoat = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int Robot = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int Shirt = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int Silvercoat = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int Strawberry = 2130771988;
			
			// aapt resource value: 0x7F010016
			public const int Train = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int Tshirt = 2130771991;
			
			// aapt resource value: 0x7F010015
			public const int TVShelf = 2130771989;
			
			// aapt resource value: 0x7F010018
			public const int Van = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int Whiteshirt = 2130771993;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int sliding_tabs = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int toolbar = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Tabbar = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int AppCompatDialogStyle = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MainTheme = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MainTheme_Base = 2130968578;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
