#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleBrowser.SfExpander.Droid.Resource", IsApplication=true)]

namespace SampleBrowser.SfExpander.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int InvoiceCalendar = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int InvoiceItem = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int InvoiceLocation = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int InvoicePaidDetails = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int People_Circle1 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int People_Circle10 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int People_Circle11 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int People_Circle12 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int People_Circle13 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int People_Circle2 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int People_Circle3 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int People_Circle4 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int People_Circle5 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int People_Circle6 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int People_Circle7 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int People_Circle8 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int People_Circle9 = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int AppCompatDialogStyle = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int MainTheme = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int MainTheme_Base = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
