#region Copyright Syncfusion® Inc. 2001-2025.
// Copyright Syncfusion® Inc. 2001-2025. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleBrowser.SfSchedule.Droid.Resource", IsApplication=false)]

namespace SampleBrowser.SfSchedule.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int cake_schedule = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int Checkup = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int Conference = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int conference_schedule = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int schedule_editor = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int scheduleview = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int stethoscope_schedule = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int troubleshoot_schedule = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
