#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleBrowser.SfListView.Droid.Resource", IsApplication=true)]

namespace SampleBrowser.SfListView.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Apple = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int Apricot = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int Avacado = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int Banana = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int Bell = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int Blueberry = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int Book0 = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int Book1 = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int Book10 = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int Book11 = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int Book12 = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int Book13 = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int Book14 = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int Book15 = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int Book16 = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int Book17 = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int Book18 = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int Book19 = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int Book2 = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int Book3 = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int Book4 = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int Book5 = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int Book6 = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int Book7 = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int Book8 = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int Book9 = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int BrownCat = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int BrownGuitar = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int Calculation = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int Cameras = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int Car = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int Cherry = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int Chocolate = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int City = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int CollegeGirl = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int CustardApple = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int DadSon = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int DiningTable = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int Dog = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int Dragon = 2130772007;
			
			// aapt resource value: 0x7F010028
			public const int Electronics = 2130772008;
			
			// aapt resource value: 0x7F010029
			public const int FacebookLine = 2130772009;
			
			// aapt resource value: 0x7F01002A
			public const int FlowerGiftCakes = 2130772010;
			
			// aapt resource value: 0x7F01002B
			public const int Food = 2130772011;
			
			// aapt resource value: 0x7F01002C
			public const int Friends = 2130772012;
			
			// aapt resource value: 0x7F01002D
			public const int GooglePlusLine = 2130772013;
			
			// aapt resource value: 0x7F01002E
			public const int Grapes = 2130772014;
			
			// aapt resource value: 0x7F01002F
			public const int Graycanvas = 2130772015;
			
			// aapt resource value: 0x7F010030
			public const int Guava = 2130772016;
			
			// aapt resource value: 0x7F010031
			public const int Guitar = 2130772017;
			
			// aapt resource value: 0x7F010032
			public const int Hight = 2130772018;
			
			// aapt resource value: 0x7F010033
			public const int Horse = 2130772019;
			
			// aapt resource value: 0x7F010034
			public const int IdealHouse = 2130772020;
			
			// aapt resource value: 0x7F010035
			public const int Jackfruit = 2130772021;
			
			// aapt resource value: 0x7F010036
			public const int Jewellery = 2130772022;
			
			// aapt resource value: 0x7F010037
			public const int Kids = 2130772023;
			
			// aapt resource value: 0x7F010038
			public const int Kiwi = 2130772024;
			
			// aapt resource value: 0x7F010039
			public const int Ladybug = 2130772025;
			
			// aapt resource value: 0x7F01003A
			public const int Lemon = 2130772026;
			
			// aapt resource value: 0x7F01003B
			public const int Lime = 2130772027;
			
			// aapt resource value: 0x7F01003C
			public const int LinkedInLine = 2130772028;
			
			// aapt resource value: 0x7F01003D
			public const int ListAutofitItems = 2130772029;
			
			// aapt resource value: 0x7F01003E
			public const int ListDataTemplateSelector = 2130772030;
			
			// aapt resource value: 0x7F01004B
			public const int Listeningmusic = 2130772043;
			
			// aapt resource value: 0x7F01003F
			public const int ListFiltering = 2130772031;
			
			// aapt resource value: 0x7F010040
			public const int ListGettingStarted = 2130772032;
			
			// aapt resource value: 0x7F010041
			public const int ListGridLayout = 2130772033;
			
			// aapt resource value: 0x7F010042
			public const int ListGrouping = 2130772034;
			
			// aapt resource value: 0x7F010043
			public const int ListItemReordering = 2130772035;
			
			// aapt resource value: 0x7F010044
			public const int ListLoadMore = 2130772036;
			
			// aapt resource value: 0x7F010045
			public const int ListOrientation = 2130772037;
			
			// aapt resource value: 0x7F010046
			public const int ListPaging = 2130772038;
			
			// aapt resource value: 0x7F010047
			public const int ListPullToRefresh = 2130772039;
			
			// aapt resource value: 0x7F010048
			public const int ListSelection = 2130772040;
			
			// aapt resource value: 0x7F010049
			public const int ListSwiping = 2130772041;
			
			// aapt resource value: 0x7F01004A
			public const int ListView = 2130772042;
			
			// aapt resource value: 0x7F01004C
			public const int Mango = 2130772044;
			
			// aapt resource value: 0x7F01004D
			public const int Minitoys = 2130772045;
			
			// aapt resource value: 0x7F01004E
			public const int Mobile = 2130772046;
			
			// aapt resource value: 0x7F01004F
			public const int Money = 2130772047;
			
			// aapt resource value: 0x7F010050
			public const int NaughtyBoy = 2130772048;
			
			// aapt resource value: 0x7F010051
			public const int Novels = 2130772049;
			
			// aapt resource value: 0x7F010052
			public const int Openbook = 2130772050;
			
			// aapt resource value: 0x7F010053
			public const int Orange = 2130772051;
			
			// aapt resource value: 0x7F010054
			public const int Papaya = 2130772052;
			
			// aapt resource value: 0x7F010055
			public const int Peach = 2130772053;
			
			// aapt resource value: 0x7F010056
			public const int Peacock = 2130772054;
			
			// aapt resource value: 0x7F010057
			public const int People_Circle0 = 2130772055;
			
			// aapt resource value: 0x7F010058
			public const int People_Circle1 = 2130772056;
			
			// aapt resource value: 0x7F010059
			public const int People_Circle10 = 2130772057;
			
			// aapt resource value: 0x7F01005A
			public const int People_Circle11 = 2130772058;
			
			// aapt resource value: 0x7F01005B
			public const int People_Circle12 = 2130772059;
			
			// aapt resource value: 0x7F01005C
			public const int People_Circle13 = 2130772060;
			
			// aapt resource value: 0x7F01005D
			public const int People_Circle14 = 2130772061;
			
			// aapt resource value: 0x7F01005E
			public const int People_Circle15 = 2130772062;
			
			// aapt resource value: 0x7F01005F
			public const int People_Circle16 = 2130772063;
			
			// aapt resource value: 0x7F010060
			public const int People_Circle17 = 2130772064;
			
			// aapt resource value: 0x7F010061
			public const int People_Circle18 = 2130772065;
			
			// aapt resource value: 0x7F010062
			public const int People_Circle19 = 2130772066;
			
			// aapt resource value: 0x7F010063
			public const int People_Circle2 = 2130772067;
			
			// aapt resource value: 0x7F010064
			public const int People_Circle3 = 2130772068;
			
			// aapt resource value: 0x7F010065
			public const int People_Circle4 = 2130772069;
			
			// aapt resource value: 0x7F010066
			public const int People_Circle5 = 2130772070;
			
			// aapt resource value: 0x7F010067
			public const int People_Circle6 = 2130772071;
			
			// aapt resource value: 0x7F010068
			public const int People_Circle7 = 2130772072;
			
			// aapt resource value: 0x7F010069
			public const int People_Circle8 = 2130772073;
			
			// aapt resource value: 0x7F01006A
			public const int People_Circle9 = 2130772074;
			
			// aapt resource value: 0x7F01006B
			public const int Perfumes = 2130772075;
			
			// aapt resource value: 0x7F01006C
			public const int Pineapple = 2130772076;
			
			// aapt resource value: 0x7F01006D
			public const int Pizza0 = 2130772077;
			
			// aapt resource value: 0x7F01006E
			public const int Pizza1 = 2130772078;
			
			// aapt resource value: 0x7F01006F
			public const int Pizza10 = 2130772079;
			
			// aapt resource value: 0x7F010070
			public const int Pizza11 = 2130772080;
			
			// aapt resource value: 0x7F010071
			public const int Pizza12 = 2130772081;
			
			// aapt resource value: 0x7F010072
			public const int Pizza13 = 2130772082;
			
			// aapt resource value: 0x7F010073
			public const int Pizza14 = 2130772083;
			
			// aapt resource value: 0x7F010074
			public const int Pizza15 = 2130772084;
			
			// aapt resource value: 0x7F010075
			public const int Pizza16 = 2130772085;
			
			// aapt resource value: 0x7F010076
			public const int Pizza17 = 2130772086;
			
			// aapt resource value: 0x7F010077
			public const int Pizza2 = 2130772087;
			
			// aapt resource value: 0x7F010078
			public const int Pizza3 = 2130772088;
			
			// aapt resource value: 0x7F010079
			public const int Pizza4 = 2130772089;
			
			// aapt resource value: 0x7F01007A
			public const int Pizza5 = 2130772090;
			
			// aapt resource value: 0x7F01007B
			public const int Pizza6 = 2130772091;
			
			// aapt resource value: 0x7F01007C
			public const int Pizza7 = 2130772092;
			
			// aapt resource value: 0x7F01007D
			public const int Pizza8 = 2130772093;
			
			// aapt resource value: 0x7F01007E
			public const int Pizza9 = 2130772094;
			
			// aapt resource value: 0x7F01007F
			public const int Playing = 2130772095;
			
			// aapt resource value: 0x7F010080
			public const int Pomegranate = 2130772096;
			
			// aapt resource value: 0x7F010081
			public const int Radio = 2130772097;
			
			// aapt resource value: 0x7F010082
			public const int Raspberry = 2130772098;
			
			// aapt resource value: 0x7F010083
			public const int Shopping = 2130772099;
			
			// aapt resource value: 0x7F010084
			public const int SkyBlue = 2130772100;
			
			// aapt resource value: 0x7F010085
			public const int SortIcon = 2130772101;
			
			// aapt resource value: 0x7F010086
			public const int Sort_Ascending = 2130772102;
			
			// aapt resource value: 0x7F010087
			public const int Sort_Decending = 2130772103;
			
			// aapt resource value: 0x7F010088
			public const int Spices1 = 2130772104;
			
			// aapt resource value: 0x7F010089
			public const int Spices2 = 2130772105;
			
			// aapt resource value: 0x7F01008A
			public const int Sports = 2130772106;
			
			// aapt resource value: 0x7F01008B
			public const int Sports_Health = 2130772107;
			
			// aapt resource value: 0x7F01008C
			public const int Strawberry = 2130772108;
			
			// aapt resource value: 0x7F01008D
			public const int Toys = 2130772109;
			
			// aapt resource value: 0x7F01008E
			public const int Train = 2130772110;
			
			// aapt resource value: 0x7F01008F
			public const int TwitterLine = 2130772111;
			
			// aapt resource value: 0x7F010090
			public const int Van = 2130772112;
			
			// aapt resource value: 0x7F010091
			public const int Violin = 2130772113;
			
			// aapt resource value: 0x7F010092
			public const int Watches = 2130772114;
			
			// aapt resource value: 0x7F010093
			public const int Watermelon = 2130772115;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int sliding_tabs = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int toolbar = 2130837505;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Tabbar = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int AppCompatDialogStyle = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int MainTheme = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int MainTheme_Base = 2130968578;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
